# Site info
title: skyhills blog
email: skyhills13@gmail.com
author: Soeun Park

# Site setting
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True

# Build settings:
markdown: kramdown

kramdown:
    input: GFM
    hard_wrap: false

highlighter: pygments
permalink: pretty
safe: true
lsi: false

paginate : 5

# Personal Info path
aboutme: 프로젝트에 대한 기록부터 잡다한 관심사에 대한 기록까지 남기는 개인 블로그   
aboutme_photo: "/images/profile.png" 